version: '3'

services:
  osjo-api:
    build: .
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=osjo-api
      - DB_USERNAME=root
      - DB_PASSWORD=osjo-root-password
      - API_STANDARDS_TREE=vnd
      - API_SUBTYPE=osjo
      - API_PREFIX=api
      - API_VERSION=v1
      - API_DEBUG=true

  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=osjo
      - MYSQL_DATABASE=osjo-api
      - MYSQL_ROOT_PASSWORD=osjo-root-password
    ports:
      - 3306:3306
